export const SHOW_FILTER_PANEL = 'SHOW_FILTER_PANEL';

export const NEXT = 'NEXT';

export const PREV = 'PREV';

export const SET_SLIDE_INDEX = 'SET_SLIDE_INDEX';

export const SET_FILTERED_DAYS = 'SET_FILTERED_DAYS';

export const SET_OFFSET = 'SET_OFFSET';

export const INIT_THIS_MONTH = 'INIT_THIS_MONTH';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

/* COVID INFO */
export const INIT_COUNTRY_SUMMARIES = 'INIT_COUNTRY_SUMMARIES';

export const INIT_NUMBER_OF_COUNTRIES = 'INIT_NUMBER_OF_COUNTRIES';

export const INIT_GLOBAL_DATA = 'INIT_GLOBAL_DATA';

export const INIT_DATE = 'INIT_DATE';

export const INIT_FLAGS = 'INIT_FLAGS';
