export const NEXT = 'NEXT';

export const PREV = 'PREV';

export const SET_OFFSET = 'SET_OFFSET';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

/* COVID INFO */
export const INIT_COUNTRIES_SUCCESS = 'INIT_COUNTRIES';

export const INIT_NUMBER_OF_COUNTRIES = 'INIT_NUMBER_OF_COUNTRIES';

/* initialize flags */
export const INIT_FLAGS = 'INIT_FLAGS';

export const INIT_FLAGS_SUCCESS = 'INIT_FLAGS_SUCCESS';

export const INIT_FLAGS_FAILURE = 'INIT_FLAGS_FAILURE';

/* FETCHING DATA */
export const INITIALIZE_LOADING = 'INITIALIZE_LOADING';

export const INIT_COUNTRIES_FAILURE = 'FETCH_PRODUCTS_FAILURE';
